# docker-compose.yml

version: '3.8'

services:
    api-gateway:
        build:
            context: ./api-gateway
        image: microservice/demo/api-gateway
        restart: "no"
        ports:
            - 8079:50049
        depends_on:
            - user

    user:
        build:
            context: ./userService
        image: microservice/demo/user
        restart: "no"
        ports:
            - 8080:50051
        depends_on:
            - mongo

    blog:
        build:
            context: ./blogService
        image: microservice/demo/blog
        restart: "no"
        ports:
            - 8081:50052
        depends_on:
            - mongo
            - user

    comment:
        build:
            context: ./commentService
        image: microservice/demo/comment
        restart: "no"
        ports:
            - 8082:50053
        depends_on:
            - mongo
            - user
            - blog

    like:
        build:
            context: ./likeService
        image: microservice/demo/like
        restart: "no"
        ports:
            - 8083:50054
        depends_on:
            - mongo
            - user
            - blog

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: microserviceTry
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

volumes:
    postgresdb:
    mysqldb:
    mongodb:
    mongodb_config: