# docker-compose.yml

version: '3.8'

services:
    api-gateway:
        build:
            context: ./api-gateway
        image: microservice/demo/api-gateway
        restart: "no"
        ports:
            - 8079:50049
        environment:
            - USER_ADDRESS=user:50051
        depends_on:
            - user

    user:
        build:
            context: ./userService
        image: microservice/demo/user
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-user
        ports:
            - 8080:50051
        depends_on:
            - mongo

    blog:
        build:
            context: ./blogService
        image: microservice/demo/blog
        restart: "no"
        environment:
            - DB_URI=mongodb://mongo:27017/
            - DB_NAME=Microservice-demo-blog
        ports:
            - 8081:50052
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: Microservice-demo-user
        ports:
            - 27017:27017
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb

volumes:
    postgresdb:
    mysqldb:
    mongodb:
    mongodb_config: